### ISSUE TITLE
Is the project still in development

### ISSUE THREAD

**Issue by dupuchba** [google/recki-ct#18]
Hello @ircmaxell ,

Thanks for your work, I personally learn a lot from this codebase (and your blog :-) ).
I just want to know if you can share your vision/roadmap for recki-ct.

Is it an experimental project or a WIP.

Thanks a lot.

**Comment by ircmaxell** [comment]
This was an experiment. For a few reasons I stopped work on this one, but I also started another series of projects based on the same philosophy:
- [php-cfg](https://github.com/ircmaxell/php-cfg) - a generic CFG implementation
- [php-types](https://github.com/ircmaxell/php-types) - A type reconstructor for PHP-CFG
- [php-optimizer](https://github.com/ircmaxell/php-optimizer) - A CFG optimizer
- [Tuli](https://github.com/ircmaxell/Tuli) - A static analysis engine based on the previous tools
- [php-security-scanner](https://github.com/ircmaxell/php-security-scanner) - a static security analyzer
- [php-compiler](https://github.com/ircmaxell/php-compiler) - A compiler

The entire chain, when taken together is basically what Recki did. The difference is that the components are modular, decoupled and generically applicable. So rather than just working on a subset of PHP, the goal is to work on all of it.

**Comment by dupuchba** [comment]
Thx a lot
